name: Build iOS IPA

on:
  push:
    branches:
      - beta
      - stable
      - internal

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Install ObjectBox dependencies
        run: bash <(curl -s https://raw.githubusercontent.com/objectbox/objectbox-dart/main/install.sh)
      
      - name: Run tests
        run: flutter test
      
      - name: Build IPA
        run: flutter build ipa --release --no-codesign
      
      - name: Upload IPA to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Flow-IPA
          path: build/ios/ipa/*.ipa
          retention-days: 30